FROM node:20-slim 
ENV PNPM_HOME="/pnpm"
ENV PATH="$PNPM_HOME:$PATH"
RUN corepack enable
WORKDIR /app

COPY package*.json ./
COPY pnpm-lock*.yaml ./
COPY configs configs
COPY src src
COPY tsconfig.json tsconfig.json

RUN --mount=type=cache,id=pnpm,target=/pnpm/store pnpm install --frozen-lockfile
RUN pnpm run build

# Use pnpm to start the app
CMD ["pnpm", "run", "start"]
